apiVersion: kargo.akuity.io/v1alpha1
kind: Project
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}

  annotations:
    kargo-pipelines.ukserp.ac.uk/component: kargo-project
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

  labels:
    component: kargo-project
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
