apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}

  annotations:
    kargo-pipelines.ukserp.ac.uk/component: kargo-warehouse
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.warehouse.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}

  labels:
    component: kargo-warehouse
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    chart: {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
    heritage: {{ .Release.Service }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.warehouse.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  subscriptions:

    # Track the main branch of the deployment repo so that freight pins the
    # deployment values and manifests
    - git:
        repoURL: {{ .Values.warehouse.valuesFreight.repoURL }}
        discoveryLimit: {{ .Values.warehouse.valuesFreight.discoveryLimit }}

    # Track auxiliary freight that may need to be patched into manifests
    {{- .Values.warehouse.freight | toYaml | nindent 4 -}}
