apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

# TODO show example of patching the airflow values (ingress url)
patches:
  - path: patches/applications.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
